/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package coursesmanagement;

import database.Connect;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import main.DragJFrame;
import notifications.WarningMessage;
import studentmanagement.NewApplication;

/**
 *
 * @author Nadun
 */
public class CoursesSelector extends javax.swing.JFrame {

    /**
     * Creates new form CoursesSelector
     */
    private static CoursesSelector instance=new CoursesSelector();
    private DefaultTableModel dtm;
    public CoursesSelector() {
        initComponents();
        dtm=(DefaultTableModel) coursesTable.getModel();
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int width=(int) dimension.getWidth();
        int height=(int) dimension.getHeight();
        this.setLocation((width/2)-342,(height/2)-227);
        DragJFrame df=new DragJFrame(this, jPanel1);
        
    }
    
    public static CoursesSelector getInstance(){
        return instance;   
    }
    
    public void showInterface(){
        retrieveData();
        instance.setVisible(true);
        searchBoxTxt.setText("");
        
        if(dtm.getRowCount()>0){
        coursesTable.setRowSelectionInterval(0, 0);
        }
    }
    
    
    private void cleanTable(){
      dtm.getDataVector().removeAllElements();
      dtm.fireTableDataChanged();
    }
    
    private void addCourse(String courseName,String institute,String city){
     
        dtm.addRow(new Object[]{courseName,institute,city});
    }
    
    public void retrieveData(){
      cleanTable();
      String query="SELECT inst.*,cour.* FROM institution inst INNER JOIN course cour ON inst.id="
                + "cour.institution_id WHERE inst.delete_status=0 AND cour.delete_status=0";
      Connect c=new Connect();
        ResultSet r=c.getQuery(query);
        try {
            while(r.next()){
           
            String courseName=r.getString("cour.name");
            String institute= r.getString("inst.name");
            String city=r.getString("inst.city");
                addCourse(courseName, institute, city);
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(CoursesSelector.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
   
    private void retrieveData(String query){
      cleanTable();
      
      Connect c=new Connect();
        ResultSet r=c.getQuery(query);
        try {
            while(r.next()){
           
            String courseName=r.getString("cour.name");
            String institute=r.getString("inst.name");
            String city=r.getString("inst.city");
            
                
                addCourse(courseName, institute, city);
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(CourseManager.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        coursesTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        okBtn = new javax.swing.JButton();
        cancelBtn1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        searchBoxTxt = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(21, 21, 41));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 350));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(30, 30, 30));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(60, 60, 60)));

        coursesTable.setBackground(new java.awt.Color(21, 21, 41));
        coursesTable.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 17)); // NOI18N
        coursesTable.setForeground(new java.awt.Color(153, 153, 153));
        coursesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course Name", "Institute", "City"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        coursesTable.setFocusable(false);
        coursesTable.setGridColor(new java.awt.Color(36, 36, 64));
        coursesTable.setRowHeight(30);
        coursesTable.setSelectionBackground(new java.awt.Color(36, 36, 64));
        coursesTable.setSelectionForeground(new java.awt.Color(204, 204, 204));
        coursesTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(coursesTable);
        if (coursesTable.getColumnModel().getColumnCount() > 0) {
            coursesTable.getColumnModel().getColumn(0).setResizable(false);
            coursesTable.getColumnModel().getColumn(0).setPreferredWidth(200);
            coursesTable.getColumnModel().getColumn(1).setResizable(false);
            coursesTable.getColumnModel().getColumn(1).setPreferredWidth(120);
            coursesTable.getColumnModel().getColumn(2).setResizable(false);
            coursesTable.getColumnModel().getColumn(2).setPreferredWidth(100);
        }

        jLabel1.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Courses List");

        jPanel2.setBackground(new java.awt.Color(21, 21, 41));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        okBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/okCircle.png"))); // NOI18N
        okBtn.setBorder(null);
        okBtn.setBorderPainted(false);
        okBtn.setFocusPainted(false);
        okBtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/okCircleSelected.png"))); // NOI18N
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });
        jPanel2.add(okBtn);

        cancelBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/CloseCircle.png"))); // NOI18N
        cancelBtn1.setBorder(null);
        cancelBtn1.setBorderPainted(false);
        cancelBtn1.setFocusPainted(false);
        cancelBtn1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/CloseCircle-selected.png"))); // NOI18N
        cancelBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtn1ActionPerformed(evt);
            }
        });
        jPanel2.add(cancelBtn1);

        jSeparator1.setBackground(new java.awt.Color(36, 36, 64));
        jSeparator1.setForeground(new java.awt.Color(36, 36, 64));

        searchBoxTxt.setBackground(new java.awt.Color(21, 21, 41));
        searchBoxTxt.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 17)); // NOI18N
        searchBoxTxt.setForeground(new java.awt.Color(102, 102, 102));
        searchBoxTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        searchBoxTxt.setCaretColor(new java.awt.Color(153, 153, 153));

        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search-1.png"))); // NOI18N
        searchBtn.setBorder(null);
        searchBtn.setFocusPainted(false);
        searchBtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search-1-selected.png"))); // NOI18N
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(searchBoxTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(388, 388, 388)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(searchBoxTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
        
        int selectedRowCount = coursesTable.getSelectedRowCount();
        int[] selectedRows=new int[selectedRowCount];
        selectedRows=coursesTable.getSelectedRows();
        
        if(dtm.getRowCount()==0){
            
        }else if(selectedRowCount==0){
        
            WarningMessage.getInstance().showInterface("Select to add");
        }else{
       
        for (int i = 0; i < selectedRowCount; i++) {
        String course=dtm.getValueAt(selectedRows[i], 0).toString();
        String institute=dtm.getValueAt(selectedRows[i], 1).toString();
        String city=dtm.getValueAt(selectedRows[i], 2).toString();
            if(!NewApplication.getInstance().isEarlyAddedCourse(course, institute, city)){
            NewApplication.getInstance().addCourse(course, institute, city);
            
            }
        }
        this.dispose();
        }
        
    }//GEN-LAST:event_okBtnActionPerformed

    private void cancelBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtn1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelBtn1ActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        String searchWord=searchBoxTxt.getText();
        
        String query="SELECT inst.*,cour.* FROM institution inst INNER JOIN course cour ON inst.id="
                + "cour.institution_id WHERE (inst.city LIKE '"+searchWord+"%' OR inst.name LIKE '"+searchWord+"%'"
                + " OR cour.name LIKE '%"+searchWord+"%') AND inst.delete_status=0 AND cour.delete_status=0";
       retrieveData(query);
       
    }//GEN-LAST:event_searchBtnActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
       
       WarningMessage.getInstance().disposeMessage();
    }//GEN-LAST:event_jPanel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CoursesSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CoursesSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CoursesSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CoursesSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CoursesSelector().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn1;
    private javax.swing.JTable coursesTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton okBtn;
    private javax.swing.JTextField searchBoxTxt;
    private javax.swing.JButton searchBtn;
    // End of variables declaration//GEN-END:variables
}
