/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import database.Connect;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Nadun
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    
    private String userName;
    private String password;
    public Login() {
        initComponents();
        
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int width=(int) dimension.getWidth();
        int height=(int) dimension.getHeight();
        this.setLocation((width/2)-226,(height/2)-112);
        DragJFrame df=new DragJFrame(this, jPanel1);
        
        getUser();
    }
    
    private void getUser(){
        String query="SELECT * FROM user";
        Connect con=new Connect();
        ResultSet r=con.getQuery(query);
        try {
            while(r.next()){
                
                userName=r.getString("user_name");
                password=r.getString("password");
            
            }
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private boolean hasError(String userN,String passWrd){
        boolean error = false;
        
        
        if(userN.equalsIgnoreCase(userName)&& !passWrd.equals(password)){
            notificationLabel.setText("Error : Incorrect password");
            error = true;
            
        }else if(!userN.equalsIgnoreCase(userName)&& passWrd.equals(password)){
            notificationLabel.setText("Error : Incorrect user name");
            error = true;
            
        }else if(!userN.equalsIgnoreCase(userName)&& !passWrd.equals(password)){
            notificationLabel.setText("Error : Incorrect user name & password");
            error = true;
               
        }else if(userN.equalsIgnoreCase(userName)&& passWrd.equals(password)){
            error = false;
        }
        
        
        return error;
        
    }
    
    private void setLoginBtnAction(){
        
        String userN=userNameTxt.getText();
        String passwrd=passwordTxt.getText();
        
        if(userN.isEmpty() || passwrd.isEmpty()){
           LoginBtn.setEnabled(false);
           
        }else if(!(userN.length()>0 && passwrd.length()>=4)){
           LoginBtn.setEnabled(false);
           
        }else{
           LoginBtn.setEnabled(true); 
           
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        cancelBtn = new javax.swing.JButton();
        passwordTxt = new javax.swing.JPasswordField();
        userNameTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LoginBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        notificationLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 83, 89));

        jDesktopPane1.setOpaque(false);

        cancelBtn.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 14)); // NOI18N
        cancelBtn.setText("Cancel");
        cancelBtn.setBorder(null);
        cancelBtn.setFocusPainted(false);
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        jDesktopPane1.add(cancelBtn);
        cancelBtn.setBounds(340, 170, 80, 30);

        passwordTxt.setBackground(new java.awt.Color(56, 57, 117));
        passwordTxt.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        passwordTxt.setForeground(new java.awt.Color(255, 255, 255));
        passwordTxt.setBorder(null);
        passwordTxt.setCaretColor(new java.awt.Color(255, 255, 255));
        passwordTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordTxtKeyReleased(evt);
            }
        });
        jDesktopPane1.add(passwordTxt);
        passwordTxt.setBounds(180, 100, 240, 30);

        userNameTxt.setBackground(new java.awt.Color(56, 57, 117));
        userNameTxt.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 15)); // NOI18N
        userNameTxt.setForeground(new java.awt.Color(255, 255, 255));
        userNameTxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        userNameTxt.setBorder(null);
        userNameTxt.setCaretColor(new java.awt.Color(255, 255, 255));
        userNameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                userNameTxtKeyReleased(evt);
            }
        });
        jDesktopPane1.add(userNameTxt);
        userNameTxt.setBounds(180, 60, 240, 30);

        jLabel4.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Password");
        jDesktopPane1.add(jLabel4);
        jLabel4.setBounds(50, 100, 110, 30);

        jLabel3.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("User Name");
        jDesktopPane1.add(jLabel3);
        jLabel3.setBounds(50, 60, 120, 30);

        LoginBtn.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 14)); // NOI18N
        LoginBtn.setText("Login");
        LoginBtn.setBorder(null);
        LoginBtn.setEnabled(false);
        LoginBtn.setFocusPainted(false);
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });
        jDesktopPane1.add(LoginBtn);
        LoginBtn.setBounds(200, 170, 80, 30);

        jLabel2.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LOGIN");
        jDesktopPane1.add(jLabel2);
        jLabel2.setBounds(140, 0, 170, 50);

        notificationLabel.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 14)); // NOI18N
        notificationLabel.setForeground(new java.awt.Color(102, 255, 102));
        jDesktopPane1.add(notificationLabel);
        notificationLabel.setBounds(90, 134, 330, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/loginBackground.png"))); // NOI18N
        jDesktopPane1.add(jLabel1);
        jLabel1.setBounds(-6, 0, 460, 230);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
        String userN=userNameTxt.getText();
        String passwrd=passwordTxt.getText();
        
        if(hasError(userN, passwrd)){
            
        }else{
            notificationLabel.setText("Loading.....");
            DashBord.getInstance().showInterface(userName);
            this.dispose();
            }
        
    }//GEN-LAST:event_LoginBtnActionPerformed

    private void userNameTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userNameTxtKeyReleased
        setLoginBtnAction();
    }//GEN-LAST:event_userNameTxtKeyReleased

    private void passwordTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordTxtKeyReleased
        setLoginBtnAction();
         
    }//GEN-LAST:event_passwordTxtKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel notificationLabel;
    private javax.swing.JPasswordField passwordTxt;
    private javax.swing.JTextField userNameTxt;
    // End of variables declaration//GEN-END:variables
}
