/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package studentmanagement;

import coursesmanagement.CourseManager;
import database.Connect;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import main.DragJFrame;

/**
 *
 * @author Nadun
 */
public class ApplicationView extends javax.swing.JFrame {

    /**
     * Creates new form ApplicationView
     */
    private DefaultTableModel dtm;
    private static ApplicationView instance=new ApplicationView();  
    public ApplicationView() {
        initComponents();
        
        dtm=(DefaultTableModel) courseTabel.getModel();
//        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
//        this.setSize(screenSize);
            DragJFrame df=new DragJFrame(this, jPanel2);
    }
    
     
    public static ApplicationView getInstance(){
        return instance;
      
    }
   

    public void showInterface(String stu_id,String name,String fullName,String barcode,String address,String dob,String nic
            ,String cardT,String mobile,String tele,String email,String guardianName,String guardianPhone,String registeredDate){
        
       instance.setVisible(true);
       
       registerDatetxt.setText(registeredDate);
       nameWithInitialsTxt.setText(name);
       fullNameTxt.setText(fullName);
       barcodeTxt.setText(barcode);
       AddressTxt.setText(address);
       dobTxt.setText(dob);
       nicTxt.setText(nic);
       cardtypeTxt.setText(cardT);
       mobileTxt.setText(mobile);
       telephoneTxt.setText(tele);
       emailTxt.setText(email);
       guardianTxt.setText(guardianName);
       guardianPhoneTxt.setText(guardianPhone);
       retrieveCourseDetails(stu_id);
        
    }
    
    private void cleanTabel(){
        dtm.getDataVector().removeAllElements();
        dtm.fireTableDataChanged();
    }
    
    private void clearText(){
        nameWithInitialsTxt.setText("");
       fullNameTxt.setText("");
       barcodeTxt.setText("");
       AddressTxt.setText("");
       dobTxt.setText("");
       nicTxt.setText("");
       cardtypeTxt.setText("");
       mobileTxt.setText("");
       telephoneTxt.setText("");
       emailTxt.setText("");
       guardianTxt.setText("");
       guardianPhoneTxt.setText("");
    }

    
    public void retrieveCourseDetails(String stuID){
      cleanTabel();
      String query="SELECT inst.*,cour.*,shc.* FROM (student_has_course shc INNER JOIN course cour ON cour.id="
              + "shc.course_id) INNER JOIN institution inst ON inst.id="
                + "cour.institution_id WHERE shc.student_id="+stuID+" AND inst.delete_status=0 AND cour.delete_status=0";
      Connect c=new Connect();
        ResultSet r=c.getQuery(query);
        try {
            while(r.next()){
            String courseName=r.getString("cour.name");
           
            String institute= r.getString("inst.name");
            String city=r.getString("inst.city");
                addCourse(courseName, institute, city);
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(CourseManager.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }
    
    private void addCourse(String courseName,String institute,String city){
        String serialNo=Integer.toString(dtm.getRowCount()+1);
        dtm.addRow(new Object[]{serialNo,courseName,institute,city});
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        interfaceHeadLine = new javax.swing.JLabel();
        interfaceIcon = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        backBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        barcodeTxt = new javax.swing.JTextField();
        fullNameTxt = new javax.swing.JTextField();
        nameWithInitialsTxt = new javax.swing.JTextField();
        telephoneTxt = new javax.swing.JTextField();
        mobileTxt = new javax.swing.JTextField();
        nicTxt = new javax.swing.JTextField();
        emailTxt = new javax.swing.JTextField();
        guardianTxt = new javax.swing.JTextField();
        guardianPhoneTxt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        AddressTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        courseTabel = new javax.swing.JTable();
        dobTxt = new javax.swing.JTextField();
        cardtypeTxt = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        registerDatetxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(7, 1, 36));
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));

        jLabel5.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Name with initials      -");

        jLabel6.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Full Name      -");

        jLabel7.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Barcode      -");

        jLabel8.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Address      -");

        jLabel9.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Date of Birth      -");

        jLabel11.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 22)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("NIC Number      -");

        jLabel13.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 22)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText(" Mobile Number      -");

        jLabel14.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 22)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Telephone Number      -");

        jLabel15.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 22)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Email Address      -");

        jLabel19.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 22)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Guardian Name      -");

        jLabel20.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 22)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Guardian Phone No      -");

        jPanel2.setBackground(new java.awt.Color(24, 25, 54));

        interfaceHeadLine.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 33)); // NOI18N
        interfaceHeadLine.setForeground(new java.awt.Color(153, 153, 153));
        interfaceHeadLine.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        interfaceHeadLine.setText("Application View");

        interfaceIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/viewInterfaceIcon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(interfaceIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(interfaceHeadLine, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(interfaceHeadLine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(interfaceIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(24, 25, 54));

        jPanel5.setBackground(new java.awt.Color(24, 25, 54));
        jPanel5.setLayout(new java.awt.GridLayout(1, 0, 4, 0));

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home.png"))); // NOI18N
        jButton5.setFocusPainted(false);
        jButton5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home-selected.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton5);

        jPanel6.setBackground(new java.awt.Color(7, 1, 36));
        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/back.png"))); // NOI18N
        backBtn.setBorder(null);
        backBtn.setBorderPainted(false);
        backBtn.setDisabledIcon(null);
        backBtn.setFocusPainted(false);
        backBtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/back-selected.png"))); // NOI18N
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel6.add(backBtn);

        cancelBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/close.png"))); // NOI18N
        cancelBtn.setBorder(null);
        cancelBtn.setFocusPainted(false);
        cancelBtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/close-selected.png"))); // NOI18N
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        jPanel6.add(cancelBtn);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        barcodeTxt.setEditable(false);
        barcodeTxt.setBackground(new java.awt.Color(7, 1, 36));
        barcodeTxt.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 17)); // NOI18N
        barcodeTxt.setForeground(new java.awt.Color(102, 102, 102));
        barcodeTxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        barcodeTxt.setBorder(null);
        barcodeTxt.setCaretColor(new java.awt.Color(153, 153, 153));
        barcodeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barcodeTxtActionPerformed(evt);
            }
        });

        fullNameTxt.setEditable(false);
        fullNameTxt.setBackground(new java.awt.Color(7, 1, 36));
        fullNameTxt.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 17)); // NOI18N
        fullNameTxt.setForeground(new java.awt.Color(102, 102, 102));
        fullNameTxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fullNameTxt.setBorder(null);
        fullNameTxt.setCaretColor(new java.awt.Color(153, 153, 153));
        fullNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullNameTxtActionPerformed(evt);
            }
        });

        nameWithInitialsTxt.setEditable(false);
        nameWithInitialsTxt.setBackground(new java.awt.Color(7, 1, 36));
        nameWithInitialsTxt.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 17)); // NOI18N
        nameWithInitialsTxt.setForeground(new java.awt.Color(102, 102, 102));
        nameWithInitialsTxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        nameWithInitialsTxt.setBorder(null);
        nameWithInitialsTxt.setCaretColor(new java.awt.Color(153, 153, 153));
        nameWithInitialsTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameWithInitialsTxtActionPerformed(evt);
            }
        });

        telephoneTxt.setEditable(false);
        telephoneTxt.setBackground(new java.awt.Color(7, 1, 36));
        telephoneTxt.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 17)); // NOI18N
        telephoneTxt.setForeground(new java.awt.Color(102, 102, 102));
        telephoneTxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        telephoneTxt.setBorder(null);
        telephoneTxt.setCaretColor(new java.awt.Color(153, 153, 153));
        telephoneTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telephoneTxtActionPerformed(evt);
            }
        });

        mobileTxt.setEditable(false);
        mobileTxt.setBackground(new java.awt.Color(7, 1, 36));
        mobileTxt.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 17)); // NOI18N
        mobileTxt.setForeground(new java.awt.Color(102, 102, 102));
        mobileTxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        mobileTxt.setBorder(null);
        mobileTxt.setCaretColor(new java.awt.Color(153, 153, 153));
        mobileTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileTxtActionPerformed(evt);
            }
        });

        nicTxt.setEditable(false);
        nicTxt.setBackground(new java.awt.Color(7, 1, 36));
        nicTxt.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 17)); // NOI18N
        nicTxt.setForeground(new java.awt.Color(102, 102, 102));
        nicTxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        nicTxt.setBorder(null);
        nicTxt.setCaretColor(new java.awt.Color(153, 153, 153));
        nicTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicTxtActionPerformed(evt);
            }
        });

        emailTxt.setEditable(false);
        emailTxt.setBackground(new java.awt.Color(7, 1, 36));
        emailTxt.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 17)); // NOI18N
        emailTxt.setForeground(new java.awt.Color(102, 102, 102));
        emailTxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        emailTxt.setBorder(null);
        emailTxt.setCaretColor(new java.awt.Color(153, 153, 153));
        emailTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTxtActionPerformed(evt);
            }
        });

        guardianTxt.setEditable(false);
        guardianTxt.setBackground(new java.awt.Color(7, 1, 36));
        guardianTxt.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 17)); // NOI18N
        guardianTxt.setForeground(new java.awt.Color(102, 102, 102));
        guardianTxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        guardianTxt.setBorder(null);
        guardianTxt.setCaretColor(new java.awt.Color(153, 153, 153));
        guardianTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardianTxtActionPerformed(evt);
            }
        });

        guardianPhoneTxt.setEditable(false);
        guardianPhoneTxt.setBackground(new java.awt.Color(7, 1, 36));
        guardianPhoneTxt.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 17)); // NOI18N
        guardianPhoneTxt.setForeground(new java.awt.Color(102, 102, 102));
        guardianPhoneTxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        guardianPhoneTxt.setBorder(null);
        guardianPhoneTxt.setCaretColor(new java.awt.Color(153, 153, 153));
        guardianPhoneTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardianPhoneTxtActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 22)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Card Type      -");

        jLabel17.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 22)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Courses      -");

        AddressTxt.setEditable(false);
        AddressTxt.setBackground(new java.awt.Color(7, 1, 36));
        AddressTxt.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 17)); // NOI18N
        AddressTxt.setForeground(new java.awt.Color(102, 102, 102));
        AddressTxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        AddressTxt.setBorder(null);
        AddressTxt.setCaretColor(new java.awt.Color(153, 153, 153));
        AddressTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressTxtActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(7, 1, 36));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        courseTabel.setBackground(new java.awt.Color(7, 1, 36));
        courseTabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(24, 25, 54)));
        courseTabel.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 17)); // NOI18N
        courseTabel.setForeground(new java.awt.Color(102, 102, 102));
        courseTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial no", "Course Name", "Institute", "City / Town"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        courseTabel.setEnabled(false);
        courseTabel.setGridColor(new java.awt.Color(24, 25, 54));
        courseTabel.setRowHeight(30);
        courseTabel.setSelectionBackground(new java.awt.Color(24, 25, 54));
        courseTabel.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(courseTabel);
        if (courseTabel.getColumnModel().getColumnCount() > 0) {
            courseTabel.getColumnModel().getColumn(0).setResizable(false);
            courseTabel.getColumnModel().getColumn(0).setPreferredWidth(10);
            courseTabel.getColumnModel().getColumn(1).setPreferredWidth(200);
            courseTabel.getColumnModel().getColumn(2).setResizable(false);
            courseTabel.getColumnModel().getColumn(2).setPreferredWidth(120);
            courseTabel.getColumnModel().getColumn(3).setResizable(false);
            courseTabel.getColumnModel().getColumn(3).setPreferredWidth(100);
        }

        dobTxt.setEditable(false);
        dobTxt.setBackground(new java.awt.Color(7, 1, 36));
        dobTxt.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 17)); // NOI18N
        dobTxt.setForeground(new java.awt.Color(102, 102, 102));
        dobTxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        dobTxt.setBorder(null);
        dobTxt.setCaretColor(new java.awt.Color(153, 153, 153));
        dobTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobTxtActionPerformed(evt);
            }
        });

        cardtypeTxt.setEditable(false);
        cardtypeTxt.setBackground(new java.awt.Color(7, 1, 36));
        cardtypeTxt.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 17)); // NOI18N
        cardtypeTxt.setForeground(new java.awt.Color(102, 102, 102));
        cardtypeTxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        cardtypeTxt.setBorder(null);
        cardtypeTxt.setCaretColor(new java.awt.Color(153, 153, 153));
        cardtypeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardtypeTxtActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 22)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Registered Date      -");

        registerDatetxt.setEditable(false);
        registerDatetxt.setBackground(new java.awt.Color(7, 1, 36));
        registerDatetxt.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 17)); // NOI18N
        registerDatetxt.setForeground(new java.awt.Color(102, 102, 102));
        registerDatetxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        registerDatetxt.setBorder(null);
        registerDatetxt.setCaretColor(new java.awt.Color(153, 153, 153));
        registerDatetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerDatetxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel17)
                            .addComponent(jLabel15)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel16)
                            .addComponent(jLabel18)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel5)))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nameWithInitialsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 807, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(guardianTxt)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(guardianPhoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(telephoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mobileTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cardtypeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(registerDatetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nicTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dobTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(barcodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AddressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 807, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fullNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 866, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 38, Short.MAX_VALUE)))
                        .addGap(50, 50, 50))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(nameWithInitialsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fullNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(barcodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dobTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nicTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerDatetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardtypeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mobileTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telephoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardianTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(guardianPhoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        StudentRegistry sr=StudentRegistry.getInstance();
        CardMarker cm=CardMarker.getInstance();
        if(sr.isVisible()){
           sr.dispose();
        }
        
        if(cm.isVisible()){
           cm.dispose();
        }
        
        clearText();
        cleanTabel();
        this.dispose();

    }//GEN-LAST:event_jButton5ActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed

        clearText();
        cleanTabel();
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        clearText();
        cleanTabel();
        this.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void barcodeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barcodeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barcodeTxtActionPerformed

    private void fullNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullNameTxtActionPerformed

    private void nameWithInitialsTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameWithInitialsTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameWithInitialsTxtActionPerformed

    private void telephoneTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telephoneTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telephoneTxtActionPerformed

    private void mobileTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobileTxtActionPerformed

    private void nicTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nicTxtActionPerformed

    private void emailTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTxtActionPerformed

    private void guardianTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardianTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guardianTxtActionPerformed

    private void guardianPhoneTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardianPhoneTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guardianPhoneTxtActionPerformed

    private void AddressTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressTxtActionPerformed

    private void dobTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobTxtActionPerformed

    private void cardtypeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardtypeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardtypeTxtActionPerformed

    private void registerDatetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerDatetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerDatetxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApplicationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApplicationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApplicationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApplicationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApplicationView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressTxt;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField barcodeTxt;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextField cardtypeTxt;
    private javax.swing.JTable courseTabel;
    private javax.swing.JTextField dobTxt;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JTextField fullNameTxt;
    private javax.swing.JTextField guardianPhoneTxt;
    private javax.swing.JTextField guardianTxt;
    private javax.swing.JLabel interfaceHeadLine;
    private javax.swing.JLabel interfaceIcon;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mobileTxt;
    private javax.swing.JTextField nameWithInitialsTxt;
    private javax.swing.JTextField nicTxt;
    private javax.swing.JTextField registerDatetxt;
    private javax.swing.JTextField telephoneTxt;
    // End of variables declaration//GEN-END:variables
}
